internal/common/downloads.go
The task to delete files from the download dir (SFTP and Reports) are deleted every 5 minutes, and keeps files that have been created in the last minute to avoid race condition.
Closes #7
=> fix: delete download dir runs every 5 minutes and keeps recent files

internal/views/typescript/package-lock.json, internal/views/typescript/package.json
esbuild has been updated to remove security warning
closes #35
=> task: update esbuild version to remove dependabot alert

internal/controllers/webserver/handlers/computers.go, internal/controllers/webserver/handlers/software.go, internal/models/apps.go, internal/models/apps_test.go, internal/views/computers_views/apps_views.templ, internal/views/filters/filter.go, internal/views/locales/en.yaml, internal/views/locales/es.yaml, internal/views/partials/brand.partials.templ, internal/views/software_views/software_views.templ
The view now has some filters:
Closes #32
=> feat: add filter to computers software view also add some brands

internal/controllers/webserver/handlers/computers.go
=> chore: update computers.go

assets/css/main.css, internal/controllers/webserver/handlers/agents.go, internal/controllers/webserver/handlers/handler.go, internal/views/agents_views/agents.templ, internal/views/computers_views/apps_views.templ, internal/views/computers_views/computer.templ, internal/views/computers_views/computers_views.templ, internal/views/computers_views/deploy_views.templ, internal/views/computers_views/logical_disks.templ, internal/views/computers_views/metadata_views.templ, internal/views/computers_views/monitor.templ, internal/views/computers_views/network_adapters.templ, internal/views/computers_views/notes_views.templ, internal/views/computers_views/operating_system.templ, internal/views/computers_views/power_views.templ, internal/views/computers_views/printers.templ, internal/views/computers_views/remote-assistance.templ, internal/views/computers_views/shares.templ, internal/views/locales/en.yaml, internal/views/locales/es.yaml, internal/views/partials/confirm_delete_agent.partials.templ
=> feat: uninstall agent when deleting from console

go.mod, go.sum, internal/views/computers_views/monitor.templ, internal/views/locales/en.yaml, internal/views/locales/es.yaml
=> feat: add week and year of monitor manufacture

go.mod, go.sum, internal/controllers/webserver/handlers/settings.go, internal/models/settings.go, internal/views/admin_views/settings.templ, internal/views/locales/en.yaml, internal/views/locales/es.yaml
=> feat: add the option to automatically admit agents

assets/css/main.css, go.mod, go.sum, internal/controllers/webserver/handlers/agents.go, internal/controllers/webserver/handlers/reports.go, internal/models/agents.go, internal/views/agents_views/agents.templ, internal/views/computers_views/computers_views.templ, internal/views/dashboard_views/dashboard.templ, internal/views/filters/filter.go, internal/views/filters/singlechoice.filter.templ, internal/views/locales/en.yaml, internal/views/locales/es.yaml
=> feat: agents can be filtered now by agents that haven't contacted

internal/models/winget/deploy.go
=> fix: wrong sqlite query for package deployment

internal/controllers/webserver/handlers/handler.go
=> fix: missing retention

internal/controllers/webserver/handlers/reports.go
=> fix: computers report

go.mod, go.sum, internal/views/dashboard_views/dashboard.templ, internal/views/locales/en.yaml, internal/views/locales/es.yaml
=> fix: unknown update status is now treated

internal/views/partials/manufacturer.partials.templ
=> feat: add hetzner manufacturer

internal/controllers/webserver/handlers/update_agents.go
=> feat: aarch64 should be converted to arm64

internal/models/smtp.go
=> task: remove bogus select in GetSMTPSettings

internal/views/computers_views/deploy_views.templ, internal/views/deploy_views/deploy_views.templ
=> fix: add autocomplete off to package search

internal/views/partials/brand.partials.templ
=> feat: new app icons

internal/views/computers_views/computer.templ, internal/views/computers_views/computers_views.templ, internal/views/partials/manufacturer.partials.templ
=> feat: raspberry and msi detection

go.mod, go.sum, internal/controllers/webserver/handlers/tasks.go, internal/models/tasks.go, internal/views/locales/en.yaml, internal/views/locales/es.yaml, internal/views/partials/powershell.partials.templ, internal/views/partials/task.select.partials.templ, internal/views/profiles_views/profiles_edit.templ, internal/views/tasks_views/tasks_edit.templ, internal/views/tasks_views/tasks_new.templ
=> feat: new powershell script task

go.mod, go.sum, internal/controllers/webserver/handlers/computers.go, internal/controllers/webserver/handlers/profiles.go, internal/controllers/webserver/handlers/tasks.go, internal/models/tasks.go, internal/views/locales/en.yaml, internal/views/locales/es.yaml, internal/views/partials/local_group.partials.templ, internal/views/partials/osbadge.partials.templ, internal/views/partials/task.select.partials.templ, internal/views/profiles_views/profiles_edit.templ, internal/views/tasks_views/tasks_edit.templ
=> feat: add Linux tasks to add or remove local groups

go.mod, go.sum, internal/controllers/webserver/handlers/flatpak.go, internal/controllers/webserver/handlers/profiles.go, internal/controllers/webserver/handlers/routes.go, internal/controllers/webserver/handlers/tasks.go, internal/models/tasks.go, internal/models/winget/deploy.go, internal/views/locales/en.yaml, internal/views/locales/es.yaml, internal/views/partials/flatpak.partials.templ, internal/views/partials/task.select.partials.templ, internal/views/profiles_views/profiles_edit.templ, internal/views/tasks_views/tasks_edit.templ
=> feat: new flatpak tasks to install and uninstall for Linux

go.mod, go.sum, internal/views/partials/task.select.partials.templ
=> feat: add local grupo and script for macOS

internal/views/locales/en.yaml, internal/views/locales/es.yaml, internal/views/profiles_views/profiles_views.templ
=> feat: profiles ready for macos and linux too

internal/views/agents_views/agents.templ
=> fix: agents templ navigation for agent name (logs and settings)

.woodpecker.yml, internal/common/cli.go
=> task: update version to 0.9.0

internal/controllers/webserver/handlers/tasks.go, internal/views/partials/package.search.partials.templ, internal/views/profiles_views/profiles_edit.templ
=> feat: add use latest version for winget install task

internal/views/locales/locales.go, internal/views/translatorForDates.go
=> feat: embed german translation add support for dates

internal/controllers/webserver/handlers/logout.go
Remove debug after @stavros-k review
=> fix: remove debug from logout

internal/views/dashboard_views/dashboard.templ, internal/views/locales/de.yaml, internal/views/locales/en.yaml, internal/views/locales/es.yaml, internal/views/security_views/antivirus_views.templ
=> Fix: dashboard links to antivirus view
